version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: greentrip
    ports:
      - "3306:3306"

  greentrip:
    build:
      context: .
    image: greentrip-image
    container_name: greentrip
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/greentrip
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
