name: Enforce Pull Requests to Main

on:
  pull_request:
    branches:
      - main

jobs:
  enforce-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR source branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "Les pull request ne sont autorisé que depuis develop."
          exit 1